### ISSUE TITLE
Links und Darstellung Publikationen

### ISSUE THREAD

**Issue by MichelleBindel** [snikproject/snik.eu#3]
- Präsentationen und die Links bei den Publikationen fehlen
- PDF-Embedding fehlt

Portraits fehlen absichtlich.

**Comment by MichelleBindel** [comment]
Links zu Publikationen hinzugefügt.
PDF-Embedding wegen Übersichtlichkeit weggelassen.

**Comment by MichelleBindel** [comment]
- [x] Poster in neuem Abschnitt als .svg einbetten (siehe HITO) (Poster liegen als .pdf im public, müssen noch konvertiert werden)
- [x] BibTex Collapsibles
- [x] Poster alle in einen Ordner für Übersichtlichkeit und Links anpassen

**Comment by KonradHoeffner** [comment]
- [x] SNIK Graph Medinfo 2019 Poster from @FranziskaJahn
- [x] SNIK Medinfo 2019 Poster from @KonradHoeffner
- [x] unpublished textless SNIK Graph Poster (the one hanging in front of the 227)

**Comment by KonradHoeffner** [comment]
Die SVGs sind zu groß und SVGZ scheint bei uns nicht zu funktionieren, daher die kleinen PNGs behalten. Vielleicht können die noch mit einer Palette geschrumpft werden.
